// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYZUhBBvFtGbaCHlvehFzVr6EUAfNqejI',
    appId: '1:322982009700:web:838cce9307296cd9593871',
    messagingSenderId: '322982009700',
    projectId: 'resto-finder-d4214',
    authDomain: 'resto-finder-d4214.firebaseapp.com',
    storageBucket: 'resto-finder-d4214.firebasestorage.app',
    measurementId: 'G-N5TB40170J',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJhEX8WRk_d0w2BaxrOKg5YtG7mGFAR3E',
    appId: '1:322982009700:ios:67f66c2a2cfcd7c0593871',
    messagingSenderId: '322982009700',
    projectId: 'resto-finder-d4214',
    storageBucket: 'resto-finder-d4214.firebasestorage.app',
    androidClientId:
        '322982009700-62fsnkdtocm7ng74ljo6kb6bkrn7a7e0.apps.googleusercontent.com',
    iosClientId:
        '322982009700-g0i9o9k95pk44lgd0otghmf7n2jia8hb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eRestaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYZUhBBvFtGbaCHlvehFzVr6EUAfNqejI',
    appId: '1:322982009700:web:57e938535fc862c2593871',
    messagingSenderId: '322982009700',
    projectId: 'resto-finder-d4214',
    authDomain: 'resto-finder-d4214.firebaseapp.com',
    storageBucket: 'resto-finder-d4214.firebasestorage.app',
    measurementId: 'G-EJ6GCXQR1J',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJhEX8WRk_d0w2BaxrOKg5YtG7mGFAR3E',
    appId: '1:322982009700:ios:67f66c2a2cfcd7c0593871',
    messagingSenderId: '322982009700',
    projectId: 'resto-finder-d4214',
    storageBucket: 'resto-finder-d4214.firebasestorage.app',
    androidClientId:
        '322982009700-62fsnkdtocm7ng74ljo6kb6bkrn7a7e0.apps.googleusercontent.com',
    iosClientId:
        '322982009700-g0i9o9k95pk44lgd0otghmf7n2jia8hb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eRestaApp',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgma96unqeJCMqpb-xwIEnYHuddy0Wkzs',
    appId: '1:322982009700:android:7d016e37400c4364593871',
    messagingSenderId: '322982009700',
    projectId: 'resto-finder-d4214',
    storageBucket: 'resto-finder-d4214.firebasestorage.app',
    // ...other fields as needed
  );
}
